<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run()
    {
        // $this->call([
        //     PermissionsTableSeeder::class,
        //     RolesTableSeeder::class,
        //     PermissionRoleTableSeeder::class,
        //     UsersTableSeeder::class,
        //     RoleUserTableSeeder::class,
        // ]);
        $data = 
        ["1 Kerjasama Tridharma - Pendidikan",
        "1 Kerjasama Tridharma - Penelitian",
        "1 Kerjasama Tridharma - Pengabdian kepada Masyarakat",
        "2.a Seleksi Mahasiswa",
        "2.b Mahasiswa Asing",
        "3.a.1) Dosen Tetap Perguruan Tinggi",
        "3.a.2) Dosen Pembimbing Utama Tugas Akhir",
        "3.a.3) Ekuivalen Waktu Mengajar Penuh (EWMP) Dosen Tetap Perguruan Tinggi",
        "3.a.4) Dosen Tidak Tetap ",
        "3.a.5) Dosen Industri/Praktisi ",
        "3.b.1) Pengakuan/Rekognisi Dosen",
        "3.b.2) Penelitian DTPS",
        "3.b.3) PkM DTPS",
        "3.b.4) Publikasi Ilmiah DTPS",
        "3.b.4) Pagelaran/Pameran/Presentasi/Publikasi Ilmiah DTPS",
        "3.b.5) Karya Ilmiah DTPS yang Disitasi",
        "3.b.6) Produk/Jasa DTPS yang Diadopsi oleh Industri/Masyarakat",
        "3.b.7) Luaran Penelitian/PkM Lainnya - HKI (Paten, Paten Sederhana)",
        "3.b.7) Luaran Penelitian/PkM Lainnya - HKI (Hak Cipta, Desain Produk Industri, dll.)",
        "3.b.7) Luaran Penelitian/PkM Lainnya - Teknologi Tepat Guna, Produk, Karya Seni, Rekayasa Sosial",
        "3.b.7) Luaran Penelitian/PkM Lainnya - Buku ber-ISBN, Book Chapter",
        "4 Penggunaan Dana",
        "5.a Kurikulum, Capaian Pembelajaran, dan Rencana Pembelajaran",
        "5.b Integrasi Kegiatan Penelitian/PkM dalam Pembelajaran",
        "5.c Kepuasan Mahasiswa",
        "6.a Penelitian DTPS yang Melibatkan Mahasiswa",
        "6.b Penelitian DTPS yang Menjadi Rujukan Tema Tesis/Disertasi",
        "7 PkM DTPS yang Melibatkan Mahasiswa",
        "8.a IPK Lulusan",
        "8.b.1) Prestasi Akademik Mahasiswa",
        "8.b.2) Prestasi Non-akademik Mahasiswa",
        "8.c Masa Studi Lulusan",
        "8.d.1) Waktu Tunggu Lulusan",
        "8.d.2) Kesesuaian Bidang Kerja Lulusan",
        "8.e.1) Tempat Kerja Lulusan",
        "Referensi 8.e.2)",
        "8.e.2) Kepuasan Pengguna Lulusan",
        "8.f.1) Publikasi Ilmiah Mahasiswa",
        "8.f.1) Pagelaran/Pameran/Presentasi/Publikasi Ilmiah Mahasiswa",
        "8.f.2) Karya Ilmiah Mahasiswa yang Disitasi",
        "8.f.3) Produk/Jasa Mahasiswa yang Diadopsi oleh Industri/Masyarakat",
        "8.f.4) Luaran Penelitian yang Dihasilkan Mahasiswa - HKI (Paten, Paten Sederhana)",
        "8.f.4) Luaran Penelitian yang Dihasilkan Mahasiswa - HKI (Hak Cipta, Desain Produk Industri, dll.)",
        "8.f.4) Luaran Penelitian yang Dihasilkan Mahasiswa -Teknologi Tepat Guna, Produk, Karya Seni, Rekayasa Sosial",
        "8.f.4) Luaran Penelitian yang Dihasilkan Mahasiswa - Buku ber-ISBN, Book Ch"];
        $fakultas = [
            "Akuntansi	D3	",
            "Keuangan, Perbankan & Asuransi	D3	",
            "Pemasaran	D3	",
            "Perpajakan	D3	",
            "Akuntansi	S1	",
            "Ekonomi Pembangunan	S1	",
            "Manajemen	S1	",
            "Ilmu Akuntansi	S2	",
            "Ilmu Ekonomi	S2	",
            "Manajemen	S2	",
            "Ilmu Ekonomi	S3",
            "Profesi Akuntansi	Sp1	",
            "Ilmu Hukum	S1	",
            "Ilmu Hukum	S2	",
            "Ilmu Hukum	S3",
            "Bimbingan Konseling	S1	",
            "Pendidikan Bahasa Dan Sastra Indonesia	S1	",
            "Pendidikan Bahasa Inggris	S1	",
            "Pendidikan Biologi	S1	",
            "Pendidikan Ekonomi	S1	",
            "Pendidikan Fisika	S1	",
            "Pendidikan Geografi	S1	",
            "Pendidikan Jasmani, Kesehatan Dan Rekreasi	S1	",
            "Pendidikan Kimia	S1	",
            "Pendidikan Matematika	S1	",
            "Pendidikan Pancasila Dan Kewarganegaraan	S1	",
            "Pendidikan Sejarah	S1	",
            "Pendidikan Seni Tari 	S1	",
            "Pendididikan Bahasa Prancis	S1",
            "Pendidikan Anak Usia Dini	S1	",
            "Pendidikan IPS	S2	",
            "Teknologi Pendidikan	S2	",
            "Manajemen Pendidikan	S2	",
            "Pendidikan Bahasa dan Sastra Indonesia	S2	",
            "Pendidikan Bahasa Dan Sastra Daerah	S2	",
            "Keguruan IPA	S2	",
            "Keguruan Guru SD	S2	",
            "Pendidikan Matematika	S2",
            "Pendidikan Bahasa Inggris	S2	",
            "Pendidikan Fisika	S2	",
            "Ilmu Pendidikan	S3",
            "Perkebunan	D3	",
            "Agribisnis	S1	",
            "Agroteknologi	S1	",
            "Budidaya Perairan	S1	",
            "Kehutanan	S1	",
            "Teknologi Hasil Pertanian	S1	",
            "Peternakan	S1	",
            "Teknik Pertanian	S1	",
            "Ilmu Tanah	S1",
            "Proteksi Tanaman	S1",
            "Agronomi	S1",
            "Penyuluhan Pertanian	S1",
            "Sumberdaya Akuatik	S1",
            "Agribisnis	S2	",
            "Agronomi	S2	",
            "Teknologi Industri Pertanian	S2	",
            "Manajemen Sumber Daya Alam	S2	",
            "Ilmu Kehutanan	S2	",
            "Teknologi Pangan	S2",
            "Ilmu Penyuluhan Pembangunan/Pemberdayaan Masyarakat	S2",
            "Penyuluhan dan Komunikasi Pertanian	S2",
            "Agroekoteknologi	S2",
            "Manajemen Wilayah Pesisir Laut	S2",
            "Perencanaan Wilayah dan Kota	S2",
            "Ilmu Lingkungan	S2	",
            "Ilmu Pertanian	S3",
            "Survei Dan Pemetaan	D3	",
            "Teknik Mesin	D3	",
            "Teknik Sipil	D3	",
            "Teknik Elektro	S1	",
            "Teknik Geofisika	S1	",
            "Teknik Kimia	S1	",
            "Teknik Mesin	S1	",
            "Teknik Sipil	S1	",
            "Teknik Arsitektur	S1",
            "Teknik Geodesi	S1",
            "Teknik Informatika	S1",
            "Teknik Sipil	S2	",
            "Teknik Mesin	S2",
            "Sekretaris	D3	",
            "Hubungan Masyarakat	D3	",
            "Perpustakaan	D3	",
            "Ilmu Komunikasi	S1	",
            "Ilmu Pemerintahan	S1	",
            "Sosiologi	S1	",
            "Administrasi Negara	S1	",
            "Administrasi Bisnis	S1	",
            "Hubungan Internasional	S1",
            "Magister Ilmu Pemerintahan	S2	",
            "Magister Ilmu Administrasi (FISIP)	S2",
            "Ilmu Komunikasi	S2",
            "Manajemen Informatika	D3	",
            "Fisika	S1	",
            "Kimia	S1	",
            "Matematika	S1	",
            "Ilmu Komputer	S1	",
            "Biologi	S1	",
            "Ilmu Kimia	S2	",
            "Ilmu Biologi	S2	",
            "Ilmu Matematika	S2",
            "Fisika	S2",
            "MIPA	S3",
            "Pendidikan Dokter	S1	",
        ];

        $lkpsUrl = ["admin.r_1_1_kerjasama_pendidikan.index","admin.r_1_3_kerjasama_pkm.index",
        "admin.r_2a_seleksi_mahasiswa_baru.index",
        "admin.r_2b_mahasiswa_asing.index",
        "admin.r_3a_1_dosen_tetap_pt.index",
        "admin.r_3a_2_dospem_utama_ta.index",
        "admin.r_3a_3_ewmp_dosen_tetap_pt.index",
        "admin.r_3a4_dosen_tidak_tetap.index",
        "admin.r_3a_2_dospem_utama_ta.index",
        "admin.r_3b1_pengakuan_dtps.index",
        "admin.r_3b2_penelitian_dtps.index",
        "admin.r_3b3_pkm_dtps.index",
        "admin.r_3b4_1_publikasi_ilmiah_dtps.index",
        "admin.r_3b4_2_pagelaran_ilmiah_dtps.index",
        "admin.r_3b5_krya_ilmiah_dtps_yg_dstasi.index",
        "admin.r_3b6_prdk_dtps_yg_diadps_indstr.index",
        "admin.r_3b7_1_luarn_pnltn_lainny_ptn.index",
        "admin.r_3b7_2_lrn_pltn_lnny_hki_hk_cpt.index",
        "admin.r_3b7_3_lrn_pnltn_lnny_tknlg_cpt.index",
        "admin.r_4_penggunaan_data.index",
        "admin.r_5a_kurikulum_capaian_pmbljrn.index",
        "admin.r_5b_integrasi_keg_penelitian.index",
        "admin.r_5c_kepuasan_mahasiswa.index",
        "admin.r_6a_pnltn_dtps_yg_mlbtkn_mhs.index",
        "admin.r_6b_pen_dtps_yg_mjd_ruj_tm_tss.index",
        "admin.r_7_pkm_dtps_yg_melibatkan_mhs.index",
        "admin.r_8a_ipk_lulusan.index",
        "admin.r_8b1_prestasi_akdmk_mhs.index",
        "admin.r_8b2_prestasi_nonakdmk_mhs.index"];
        $lkps = DB::table('m_lkps')->get();
        foreach ($lkps as $key => $value) {
            if(isset($lkpsUrl[$key])){
                $lkps = DB::table('m_lkps')->where('id',$value->id)->update(['url' => $lkpsUrl[$key]]);
            }
            // DB::table('users')->insert([
            //     'name' => $value,
            //     'email' => preg_replace('/\s+/', '_',strtolower($value)).'@staff.com',
            //     'password' => bcrypt('123456'),
            //     'created_at' => Carbon::now()
                
            // ]);
        }
    }
}
