"admin.r_1_3_kerjasama_pkm.index",
"admin.r_2a_seleksi_mahasiswa_baru.index",
"admin.r_2b_mahasiswa_asing.index",
"admin.r_3a_1_dosen_tetap_pt.index",
"admin.r_3a_2_dospem_utama_ta.index",
"admin.r_3a_3_ewmp_dosen_tetap_pt.index",
"admin.r_3a4_dosen_tidak_tetap.index",
"admin.r_3a_2_dospem_utama_ta.index",
"admin.r_3b1_pengakuan_dtps.index",
"admin.r_3b2_penelitian_dtps.index",
"admin.r_3b3_pkm_dtps.index",
"admin.r_3b4_1_publikasi_ilmiah_dtps.index",
"admin.r_3b4_2_pagelaran_ilmiah_dtps.index",
"admin.r_3b6_prdk_dtps_yg_diadps_indstr.index",
"admin.r_3b7_1_luarn_pnltn_lainny_ptn.index",
"admin.r_3b7_2_lrn_pltn_lnny_hki_hk_cpt.index",
"admin.r_3b7_3_lrn_pnltn_lnny_tknlg_cpt.index",
"admin.r_4_penggunaan_data.index",
"admin.r_5a_kurikulum_capaian_pmbljrn.index",
"admin.r_5b_integrasi_keg_penelitian.index",
"admin.r_5c_kepuasan_mahasiswa.index",
"admin.r_6a_pnltn_dtps_yg_mlbtkn_mhs.index",
"admin.r_6b_pen_dtps_yg_mjd_ruj_tm_tss.index",
"admin.r_7_pkm_dtps_yg_melibatkan_mhs.index",
"admin.r_8a_ipk_lulusan.index",
"admin.r_8b1_prestasi_akdmk_mhs.index",
"admin.r_8b2_prestasi_nonakdmk_mhs.index",



admin.r_8c_masastudi_llsn_dip.index
admin.r_8c_masastudi_llsn_srj.index
admin.r_8c_masastudi_llsn_mgr.index
admin.r_8c_masastudi_lllsn_dok.index
admin.r_8d1_wkt_llsn_dip.index
admin.r_8d1_wkt_llsn_srj.index
admin.r_8d1_wkt_llsn_sjter.index
admin.r_8e1_tmp_krj_lulusan.index
admin.r_8e2_kepuasan_pgn_llsn.index
admin.r_8f1_1_publks_ilmiah_mhs.index
admin.r_8f1_2_pglrn_ilmiah_mhs.index
admin.r_8f2_kry_ilmiah_mhs_dsts.index
admin.r_8f3_produk_dtps_mhs.index
admin.r_8f4_1_luaran_penelitian_mp.index
admin.r_8f4_2_luaran_penelitian_mhc.index
admin.r_8f4_3_luaran_penelitian_ttg.index
admin.r_8f4_4_luaran_penelitian_isbn.index
